In [1]:
import requests
import time 
import pandas as pd

from bs4 import BeautifulSoup

In [2]:
# I still worked with the renewablesm this data was also taked from OECD (https://data.oecd.org/energy/renewable-energy.htm#indicator-chart), 
# but I am not insisting on this topic:
all_renewables = pd.read_csv('C:/Users/zirav/Desktop/Accenture/My_final_project/renewable_capacity_timeseries.csv', encoding="UTF-8")
all_renewables.head()

,day,CH_bioenergy_capacity,CH_solar_capacity,CH_wind_onshore_capacity,DE_bioenergy_capacity,DE_geothermal_capacity,DE_solar_capacity,DE_wind_capacity,DE_wind_offshore_capacity,DE_wind_onshore_capacity,...,GB-UKM_bioenergy_capacity,GB-UKM_hydro_capacity,GB-UKM_marine_capacity,GB-UKM_solar_capacity,GB-UKM_wind_capacity,GB-UKM_wind_offshore_capacity,GB-UKM_wind_onshore_capacity,SE_wind_capacity,SE_wind_offshore_capacity,SE_wind_onshore_capacity
0,1900-01-01,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1900-01-02,0.0,0.0,0.0,0.08,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1900-01-03,0.0,0.0,0.0,0.08,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1900-01-04,0.0,0.0,0.0,0.08,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1900-01-05,0.0,0.0,0.0,0.08,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [3]:
# check the final part of the table
all_renewables.tail()

,day,CH_bioenergy_capacity,CH_solar_capacity,CH_wind_onshore_capacity,DE_bioenergy_capacity,DE_geothermal_capacity,DE_solar_capacity,DE_wind_capacity,DE_wind_offshore_capacity,DE_wind_onshore_capacity,...,GB-UKM_bioenergy_capacity,GB-UKM_hydro_capacity,GB-UKM_marine_capacity,GB-UKM_solar_capacity,GB-UKM_wind_capacity,GB-UKM_wind_offshore_capacity,GB-UKM_wind_onshore_capacity,SE_wind_capacity,SE_wind_offshore_capacity,SE_wind_onshore_capacity
44161,2020-11-28,87.165,620.399,64.173,8021.331,51.094,50508.38,50451.642,5741.634,44710.008,...,6737.7,3442.6,34.5,8468.3,23020.0,9692.7,13327.3,9514.16,191.15,9323.01
44162,2020-11-29,87.165,620.399,64.173,8021.331,51.094,50508.38,50451.642,5741.634,44710.008,...,6737.7,3442.6,34.5,8468.3,23020.0,9692.7,13327.3,9514.16,191.15,9323.01
44163,2020-11-30,87.165,620.399,64.173,8021.331,51.094,50508.38,50451.642,5741.634,44710.008,...,6737.7,3442.6,34.5,8468.3,23020.0,9692.7,13327.3,9514.16,191.15,9323.01
44164,2020-12-01,87.165,620.399,64.173,8021.331,51.094,50508.38,50451.642,5741.634,44710.008,...,6737.7,3442.6,34.5,8468.3,23020.0,9692.7,13327.3,9514.16,191.15,9323.01
44165,2020-12-02,87.165,620.399,64.173,8021.331,51.094,50508.38,50451.642,5741.634,44710.008,...,6737.7,3442.6,34.5,8473.3,23020.0,9692.7,13327.3,9514.16,191.15,9323.01

In [4]:
all_renewables.shape
all_renewables.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44166 entries, 0 to 44165
Data columns (total 40 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   day                            44166 non-null  object
 1   CH_bioenergy_capacity          44166 non-null  float64
 2   CH_solar_capacity              44166 non-null  float64
 3   CH_wind_onshore_capacity       44166 non-null  float64
 4   DE_bioenergy_capacity          44166 non-null  float64
 5   DE_geothermal_capacity         44166 non-null  float64
 6   DE_solar_capacity              44166 non-null  float64
 7   DE_wind_capacity               44166 non-null  float64
 8   DE_wind_offshore_capacity      44166 non-null  float64
 9   DE_wind_onshore_capacity       44166 non-null  float64
 10  DK_solar_capacity              44166 non-null  float64
 11  DK_wind_capacity               44166 non-null  float64
 12  DK_wind_offshore_capacity      44166 non-null  float64
 13  DK_wind_onshore_capacity       44166 non-null  float64
 14  FR_bioenergy_capacity          44166 non-null  float64
 15  FR_geothermal_capacity         44166 non-null  float64
 16  FR_hydro_capacity              44166 non-null  float64
 17  FR_marine_capacity             44166 non-null  float64
 18  FR_solar_capacity              44166 non-null  float64
 19  FR_wind_onshore_capacity       44166 non-null  float64
 20  GB-GBN_bioenergy_capacity      44166 non-null  float64
 21  GB-GBN_hydro_capacity          44166 non-null  float64
 22  GB-GBN_marine_capacity         44166 non-null  float64
 23  GB-GBN_solar_capacity          44166 non-null  float64
 24  GB-GBN_wind_capacity           44166 non-null  float64
 25  GB-GBN_wind_offshore_capacity  44166 non-null  float64
 26  GB-GBN_wind_onshore_capacity   44166 non-null  float64
 27  GB-NIR_bioenergy_capacity      44166 non-null  float64
 28  GB-NIR_solar_capacity          44166 non-null  float64
 29  GB-NIR_wind_onshore_capacity   44166 non-null  float64
 30  GB-UKM_bioenergy_capacity      44166 non-null  float64
 31  GB-UKM_hydro_capacity          44166 non-null  float64
 32  GB-UKM_marine_capacity         44166 non-null  float64
 33  GB-UKM_solar_capacity          44166 non-null  float64
 34  GB-UKM_wind_capacity           44166 non-null  float64
 35  GB-UKM_wind_offshore_capacity  44166 non-null  float64
 36  GB-UKM_wind_onshore_capacity   44166 non-null  float64
 37  SE_wind_capacity               44166 non-null  float64
 38  SE_wind_offshore_capacity      44166 non-null  float64
 39  SE_wind_onshore_capacity       44166 non-null  float64
dtypes: float64(39), object(1)
memory usage: 13.5+ MB

In [5]:
# for further extracting year 
all_renewables.index = all_renewables.day
all_renewables.head()

,day,CH_bioenergy_capacity,CH_solar_capacity,CH_wind_onshore_capacity,DE_bioenergy_capacity,DE_geothermal_capacity,DE_solar_capacity,DE_wind_capacity,DE_wind_offshore_capacity,DE_wind_onshore_capacity,...,GB-UKM_bioenergy_capacity,GB-UKM_hydro_capacity,GB-UKM_marine_capacity,GB-UKM_solar_capacity,GB-UKM_wind_capacity,GB-UKM_wind_offshore_capacity,GB-UKM_wind_onshore_capacity,SE_wind_capacity,SE_wind_offshore_capacity,SE_wind_onshore_capacity
day,,,,,,,,,,,,,,,,,,,,,
1900-01-01,1900-01-01,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1900-01-02,1900-01-02,0.0,0.0,0.0,0.08,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1900-01-03,1900-01-03,0.0,0.0,0.0,0.08,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1900-01-04,1900-01-04,0.0,0.0,0.0,0.08,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1900-01-05,1900-01-05,0.0,0.0,0.0,0.08,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [6]:
all_renewables['day']= pd.to_datetime(all_renewables['day'])
all_renewables.head()

,day,CH_bioenergy_capacity,CH_solar_capacity,CH_wind_onshore_capacity,DE_bioenergy_capacity,DE_geothermal_capacity,DE_solar_capacity,DE_wind_capacity,DE_wind_offshore_capacity,DE_wind_onshore_capacity,...,GB-UKM_bioenergy_capacity,GB-UKM_hydro_capacity,GB-UKM_marine_capacity,GB-UKM_solar_capacity,GB-UKM_wind_capacity,GB-UKM_wind_offshore_capacity,GB-UKM_wind_onshore_capacity,SE_wind_capacity,SE_wind_offshore_capacity,SE_wind_onshore_capacity
day,,,,,,,,,,,,,,,,,,,,,
1900-01-01,1900-01-01,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1900-01-02,1900-01-02,0.0,0.0,0.0,0.08,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1900-01-03,1900-01-03,0.0,0.0,0.0,0.08,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1900-01-04,1900-01-04,0.0,0.0,0.0,0.08,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1900-01-05,1900-01-05,0.0,0.0,0.0,0.08,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [37]:
# extracting year
all_renewables['year'] = pd.DatetimeIndex(all_renewables['day']).year
all_renewables.tail()

,day,CH_bioenergy_capacity,CH_solar_capacity,CH_wind_onshore_capacity,DE_bioenergy_capacity,DE_geothermal_capacity,DE_solar_capacity,DE_wind_capacity,DE_wind_offshore_capacity,DE_wind_onshore_capacity,...,GB-UKM_hydro_capacity,GB-UKM_marine_capacity,GB-UKM_solar_capacity,GB-UKM_wind_capacity,GB-UKM_wind_offshore_capacity,GB-UKM_wind_onshore_capacity,SE_wind_capacity,SE_wind_offshore_capacity,SE_wind_onshore_capacity,year
day,,,,,,,,,,,,,,,,,,,,,
2020-11-28,2020-11-28,87.165,620.399,64.173,8021.331,51.094,50508.38,50451.642,5741.634,44710.008,...,3442.6,34.5,8468.3,23020.0,9692.7,13327.3,9514.16,191.15,9323.01,2020
2020-11-29,2020-11-29,87.165,620.399,64.173,8021.331,51.094,50508.38,50451.642,5741.634,44710.008,...,3442.6,34.5,8468.3,23020.0,9692.7,13327.3,9514.16,191.15,9323.01,2020
2020-11-30,2020-11-30,87.165,620.399,64.173,8021.331,51.094,50508.38,50451.642,5741.634,44710.008,...,3442.6,34.5,8468.3,23020.0,9692.7,13327.3,9514.16,191.15,9323.01,2020
2020-12-01,2020-12-01,87.165,620.399,64.173,8021.331,51.094,50508.38,50451.642,5741.634,44710.008,...,3442.6,34.5,8468.3,23020.0,9692.7,13327.3,9514.16,191.15,9323.01,2020
2020-12-02,2020-12-02,87.165,620.399,64.173,8021.331,51.094,50508.38,50451.642,5741.634,44710.008,...,3442.6,34.5,8473.3,23020.0,9692.7,13327.3,9514.16,191.15,9323.01,2020

In [7]:
# The values could be modified finding the mean values by years for each country and type of renews, then fort he first step to get either a total graph 
# of all these indicators changing within the last century (this graph should be very complicated from the visual point of view) or different graphs 
# also by years, by countries, by types of renews. 

# with this small code I simply checked myself ))
all_renewables.loc['2020-01-01':'2020-12-02', 'CH_bioenergy_capacity':'CH_wind_onshore_capacity']

            CH_bioenergy_capacity  CH_solar_capacity  CH_wind_onshore_capacity
day
2020-01-01                 87.165            620.399                    64.173
2020-01-02                 87.165            620.399                    64.173
2020-01-03                 87.165            620.399                    64.173
2020-01-04                 87.165            620.399                    64.173
2020-01-05                 87.165            620.399                    64.173
...                           ...                ...                       ...
2020-11-28                 87.165            620.399                    64.173
2020-11-29                 87.165            620.399                    64.173
2020-11-30                 87.165            620.399                    64.173
2020-12-01                 87.165            620.399                    64.173
2020-12-02                 87.165            620.399                    64.173

[337 rows x 3 columns]

Further I suppose we could also find the data on the demands of the Eurpean countries in energy by years and than for the later years compare for what part (in %, for example) each of the countries could cover its demands by renewables and , may be, as You suggested before, make a model to predict in what time (how many years) they could cover it for, perhaps, 30 or 50 % ... This was why I asked about an opportunity to compare two different data frames.

Except this latter prediction, all the other tasks seem not very complex. But the prediction seems complex for me as I still have no idea how to realise prediction in pandas.